title: En Passant Engine Dev Blog
description: A  blog of how I created a GUI chess engine from scratch
theme: just-the-docs

url: https://boundlessfate.github.io/EnPassantEngineBlog

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
